### ISSUE TITLE
Model training question (batch cut samples)

### ISSUE THREAD

**Issue by MLo7Ghinsan** [prophesier/diff-svc#19]
So as the title said, I batch cut my samples so they'd be short enough to not consume all my colab ram. That left me with the question of would it affect the model's output generation if I train my model with data that has the cut off at the end and start mid vowel/consonant?

**Comment by prophesier** [comment]
It may affect the performance of your model (more or less), so it's better to use a more intelligent slicer to cut at the slient part of the audio.

**Comment by MLo7Ghinsan** [comment]
Ah i see, thank you for replying
