### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Esperanza284** [prophesier/diff-svc#26]
![aq](https://user-images.githubusercontent.com/93857672/203462180-a80e7d21-b7d9-43ac-b231-cd5f149a5165.png)

**Comment by zhuangqirong** [comment]
请问您成功解决了吗？

**Comment by Esperanza284** [comment]
训练集过小
&nbsp;


千里马(nihility)
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 中午11:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [prophesier/diff-svc] IndexError: list index out of range (Issue #26)





 
请问您成功解决了吗？
