### ISSUE TITLE
IndexError: list index out of range (when uploading my model in the Inference Notebook)

### ISSUE THREAD

**Issue by RiccardoRuggiero** [prophesier/diff-svc#52]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-3-1dc7089a1746>](https://localhost:8080/#) in <module>
     50 config_path="/content/drive/MyDrive/diff-svc/data/My_Model/config.yaml" #@param {type: "string"}
     51 hubert_gpu=True
---> 52 svc_model = Svc(project_name,config_path,hubert_gpu, model_path)
     53 print('model loaded')

[/content/diff-svc/preprocessing/hubertinfer.py](https://localhost:8080/#) in __init__(self, pt_path)
     20             self.hbt_model = load_model(pt_path)
     21         else:
---> 22             pt_path = list(Path(pt_path).parent.rglob('*.pt'))[0]
     23             if 'hubert_gpu' in hparams.keys():
     24                 self.use_gpu = hparams['hubert_gpu']

IndexError: list index out of range

**Comment by JinEui-Kim** [comment]
if you don't have hubert model ckpt, the problem occur.
you have to download model ckpt.

**Comment by RiccardoRuggiero** [comment]
How can i download it?

**Comment by JinEui-Kim** [comment]
join the discord server
you can see the pre-trained-model channel
model ckpt is there

**Comment by RiccardoRuggiero** [comment]
How can i join the discord server? It seems they closed it
