### ISSUE TITLE
qq 频道码不能用

### ISSUE THREAD

**Issue by panxin801** [prophesier/diff-svc#55]
您好，
      感谢您的工作和分享，但是README中频道码现在不能用了，请问怎么能够下载预训练模型吗？谢谢，期待您的回复。

**Comment by chenxuetao** [comment]
> 您好， 感谢您的工作和分享，但是README中频道码现在不能用了，请问怎么能够下载预训练模型吗？谢谢，期待您的回复。

You may download checkpoints here: 
https://huggingface.co/spaces/Silentlin/DiffSinger/tree/763ca1e1a7a92b8590aeafb592f6bcf520c95511/checkpoints

**Comment by panxin801** [comment]
Understand , thank you a lot
