### ISSUE TITLE
is there any way to resume training?

### ISSUE THREAD

**Issue by Mixomo** [prophesier/diff-svc#63]
Hi! i need to know if there is a way to resume the training of a model. i have the ckpt and the config.yaml. do i have to point a specific path inside the config.yaml that is in the training directory? thanks!

**Comment by kin0303** [comment]
Hi @Mixomo, have you found a way to resume training?

**Comment by Mixomo** [comment]
> Hi @Mixomo, have you found a way to resume training?

Hi. I haven't used diff SVC for a while, but I think that to resume the training, you need to load the dataset (or the binary.7z which would have the dataset already processed, and having it generated and exported was optional) and then indicate all the same routes as in your previous training including the route where the checkpoint is located and the config.yaml. Diff SVC should detect the checkpoint and continue the training normally.
I hope I helped you!

PS: if instead of the dstaset, you load the binary, you don't need to preprocess everything again and you can skip that step.
